# Template for comunion developer 

[server.http]
    port = 9001
[server.grpc]
    port = 9002
[server.governor]
    port = 9003

[ceres.mysql]
    connMaxLifetime = 300
    debug = true
    dsn = "root:Comunion2021@tcp(127.0.0.1:3306)/comunion?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=5s&writeTimeout=5s"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
[ceres.redis]
    debug = true
    mode = "stub"
    addr = "127.0.0.1:6379"

[ceres.minio]
    accessKey = ""
    secretKey = ""
    endpoint = ""
    bucket = ""

[ceres.logger]
    debug = true
    level = "debug"

[ceres.oauth.github]
    clientID = ""
    clientSecret = ""
    callbackURL = ""

[ceres.oauth.google]
    clientID = ""
    clientSecret = ""
    callbackURL = ""
    
[ceres.oauth.facebook]
    clientID = ""
    clientSecret = ""
    callbackURL = ""

[ceres.sequence]
    epoch = 1626023857

[ceres.jwt]
    # expired in 72 hours
    expired = 259200
    secret = "Comunion-Ceres"

[ceres.eth]
    epoch = 0
    #endPoint = "wss://goerli.infura.io/ws/v3"
    endPoint = "wss://api.avax-test.network/ext/bc/C/ws"
    #infuraKey = "b55f1af18d6e438e96ed174494a223a8"
    startupContractAddress = "0x447336D5e7E594DB2f8C72FF54aF34557d2Da752"

[ceres.aws]
    accessKey = ""
    accessSecret = ""
    endPoint = ""
    bucket = ""
    region = ""
    maxSize = 1024000